# -*- coding: utf-8 -*-
"""credit_risk@streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYl_Bhxos4wBJCbGoZuP3f0aMzu4bJVA
"""

import streamlit as st
import pandas as pd
import joblib
import shap
import matplotlib.pyplot as plt
import numpy as np

# Loading artifacts

model = joblib.load("model.pkl")
preprocessor = joblib.load("preprocessor.pkl")
feature_names = joblib.load("feature_names.pkl")
explainer = joblib.load("explainer.pkl")

st.set_page_config(page_title="Explainable Credit Risk System", layout="wide")

st.title("🏦 Explainable Credit Risk Scoring System")
st.write("XGBoost + SHAP | Full Dataset Deployment")

# Sidebar inputs (REALISTIC)

st.sidebar.header("Loan Application Details")

duration = st.sidebar.slider("Loan Duration (months)", 6, 72, 24)
credit_amount = st.sidebar.slider("Credit Amount", 250, 20000, 5000)
age = st.sidebar.slider("Age", 18, 75, 35)
installment_rate = st.sidebar.slider("Installment Rate (%)", 1, 4, 2)
existing_credits = st.sidebar.slider("Existing Credits", 1, 4, 1)


# Building full input row

input_dict = {
    "duration": duration,
    "credit_amount": credit_amount,
    "age": age,
    "installment_rate": installment_rate,
    "existing_credits": existing_credits
}

input_df = pd.DataFrame([input_dict])

# Fill remaining categorical / missing columns safely
for col in preprocessor.feature_names_in_:
    if col not in input_df.columns:
        input_df[col] = "A"

# Ensure correct column order
input_df = input_df[preprocessor.feature_names_in_]


# Prediction

if st.button("Predict Credit Risk"):
    X_proc = preprocessor.transform(input_df)
    pd_prob = model.predict_proba(X_proc)[0][1]

    st.subheader("📊 Prediction Result")
    st.metric("Probability of Default", f"{pd_prob:.2%}")

    if pd_prob > 0.6:
        st.error("❌ High Risk – Loan Rejected")
    elif pd_prob > 0.35:
        st.warning("⚠️ Medium Risk – Manual Review")
    else:
        st.success("✅ Low Risk – Loan Approved")


    # SHAP Local Explanation

    st.subheader("🔍 Local Explanation (SHAP)")

    shap_values = explainer(X_proc)

    fig, ax = plt.subplots(figsize=(8, 5))
    shap.plots.waterfall(
        shap.Explanation(
            values=shap_values[0].values,
            base_values=shap_values[0].base_values,
            data=X_proc[0],
            feature_names=feature_names
        ),
        show=False
    )
    st.pyplot(fig)